//
// *****************************************************************
// Copyright 2021 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// *****************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: model-runtime.proto

package mmesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeStatusResponse_Status int32

const (
	RuntimeStatusResponse_STARTING RuntimeStatusResponse_Status = 0
	RuntimeStatusResponse_READY    RuntimeStatusResponse_Status = 1
	RuntimeStatusResponse_FAILING  RuntimeStatusResponse_Status = 2 //not used yet
)

// Enum value maps for RuntimeStatusResponse_Status.
var (
	RuntimeStatusResponse_Status_name = map[int32]string{
		0: "STARTING",
		1: "READY",
		2: "FAILING",
	}
	RuntimeStatusResponse_Status_value = map[string]int32{
		"STARTING": 0,
		"READY":    1,
		"FAILING":  2,
	}
)

func (x RuntimeStatusResponse_Status) Enum() *RuntimeStatusResponse_Status {
	p := new(RuntimeStatusResponse_Status)
	*p = x
	return p
}

func (x RuntimeStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_model_runtime_proto_enumTypes[0].Descriptor()
}

func (RuntimeStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_model_runtime_proto_enumTypes[0]
}

func (x RuntimeStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeStatusResponse_Status.Descriptor instead.
func (RuntimeStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{9, 0}
}

type LoadModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId   string `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=modelType,proto3" json:"modelType,omitempty"`
	ModelPath string `protobuf:"bytes,3,opt,name=modelPath,proto3" json:"modelPath,omitempty"`
	ModelKey  string `protobuf:"bytes,4,opt,name=modelKey,proto3" json:"modelKey,omitempty"`
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *LoadModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *LoadModelRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *LoadModelRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *LoadModelRequest) GetModelKey() string {
	if x != nil {
		return x.ModelKey
	}
	return ""
}

type LoadModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// OPTIONAL - If nontrivial cost is involved in
	// determining the size, return 0 here and
	// do the sizing in the modelSize function
	SizeInBytes uint64 `protobuf:"varint,1,opt,name=sizeInBytes,proto3" json:"sizeInBytes,omitempty"`
	// EXPERIMENTAL - Applies only if limitModelConcurrency = true
	// was returned from runtimeStatus rpc.
	// See RuntimeStatusResponse.limitModelConcurrency for more detail
	MaxConcurrency uint32 `protobuf:"varint,2,opt,name=maxConcurrency,proto3" json:"maxConcurrency,omitempty"`
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *LoadModelResponse) GetSizeInBytes() uint64 {
	if x != nil {
		return x.SizeInBytes
	}
	return 0
}

func (x *LoadModelResponse) GetMaxConcurrency() uint32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

type UnloadModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId string `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *UnloadModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type UnloadModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnloadModelResponse) Reset() {
	*x = UnloadModelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelResponse) ProtoMessage() {}

func (x *UnloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelResponse) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{3}
}

type PredictModelSizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId   string `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	ModelType string `protobuf:"bytes,2,opt,name=modelType,proto3" json:"modelType,omitempty"`
	ModelPath string `protobuf:"bytes,3,opt,name=modelPath,proto3" json:"modelPath,omitempty"`
	ModelKey  string `protobuf:"bytes,4,opt,name=modelKey,proto3" json:"modelKey,omitempty"`
}

func (x *PredictModelSizeRequest) Reset() {
	*x = PredictModelSizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictModelSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictModelSizeRequest) ProtoMessage() {}

func (x *PredictModelSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictModelSizeRequest.ProtoReflect.Descriptor instead.
func (*PredictModelSizeRequest) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *PredictModelSizeRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PredictModelSizeRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *PredictModelSizeRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *PredictModelSizeRequest) GetModelKey() string {
	if x != nil {
		return x.ModelKey
	}
	return ""
}

type PredictModelSizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SizeInBytes uint64 `protobuf:"varint,1,opt,name=sizeInBytes,proto3" json:"sizeInBytes,omitempty"`
}

func (x *PredictModelSizeResponse) Reset() {
	*x = PredictModelSizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictModelSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictModelSizeResponse) ProtoMessage() {}

func (x *PredictModelSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictModelSizeResponse.ProtoReflect.Descriptor instead.
func (*PredictModelSizeResponse) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *PredictModelSizeResponse) GetSizeInBytes() uint64 {
	if x != nil {
		return x.SizeInBytes
	}
	return 0
}

type ModelSizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId string `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
}

func (x *ModelSizeRequest) Reset() {
	*x = ModelSizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSizeRequest) ProtoMessage() {}

func (x *ModelSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSizeRequest.ProtoReflect.Descriptor instead.
func (*ModelSizeRequest) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *ModelSizeRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type ModelSizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SizeInBytes uint64 `protobuf:"varint,1,opt,name=sizeInBytes,proto3" json:"sizeInBytes,omitempty"`
}

func (x *ModelSizeResponse) Reset() {
	*x = ModelSizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSizeResponse) ProtoMessage() {}

func (x *ModelSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSizeResponse.ProtoReflect.Descriptor instead.
func (*ModelSizeResponse) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *ModelSizeResponse) GetSizeInBytes() uint64 {
	if x != nil {
		return x.SizeInBytes
	}
	return 0
}

type RuntimeStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuntimeStatusRequest) Reset() {
	*x = RuntimeStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStatusRequest) ProtoMessage() {}

func (x *RuntimeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStatusRequest.ProtoReflect.Descriptor instead.
func (*RuntimeStatusRequest) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{8}
}

type RuntimeStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status RuntimeStatusResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=mmesh.RuntimeStatusResponse_Status" json:"status,omitempty"`
	// memory capacity for static loaded models, in bytes
	CapacityInBytes uint64 `protobuf:"varint,2,opt,name=capacityInBytes,proto3" json:"capacityInBytes,omitempty"`
	// maximum number of model loads that can be in-flight at the same time
	MaxLoadingConcurrency uint32 `protobuf:"varint,3,opt,name=maxLoadingConcurrency,proto3" json:"maxLoadingConcurrency,omitempty"`
	// timeout for model loads in milliseconds
	ModelLoadingTimeoutMs uint32 `protobuf:"varint,4,opt,name=modelLoadingTimeoutMs,proto3" json:"modelLoadingTimeoutMs,omitempty"`
	// conservative "default" model size,
	// such that "most" models are smaller than this
	DefaultModelSizeInBytes uint64 `protobuf:"varint,5,opt,name=defaultModelSizeInBytes,proto3" json:"defaultModelSizeInBytes,omitempty"`
	// version string for this model server code
	RuntimeVersion string `protobuf:"bytes,6,opt,name=runtimeVersion,proto3" json:"runtimeVersion,omitempty"`
	// DEPRECATED - the value of this field is not used,
	// it will be removed in a future update
	NumericRuntimeVersion uint64 `protobuf:"varint,7,opt,name=numericRuntimeVersion,proto3" json:"numericRuntimeVersion,omitempty"`
	// optional, EXPERIMENTAL and subject to change
	MethodInfos map[string]*RuntimeStatusResponse_MethodInfo `protobuf:"bytes,8,rep,name=methodInfos,proto3" json:"methodInfos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// EXPERIMENTAL - Set to true to enable the mode where
	// each loaded model reports a maximum inferencing
	// concurrency via the maxConcurrency field of
	// the LoadModelResponse message. Additional requests
	// are queued in the modelmesh framework. Turning this
	// on will also enable latency-based autoscaling for
	// the models, which attempts to minimize request
	// queueing time and requires no other configuration/tuning.
	LimitModelConcurrency bool `protobuf:"varint,9,opt,name=limitModelConcurrency,proto3" json:"limitModelConcurrency,omitempty"`
}

func (x *RuntimeStatusResponse) Reset() {
	*x = RuntimeStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStatusResponse) ProtoMessage() {}

func (x *RuntimeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStatusResponse.ProtoReflect.Descriptor instead.
func (*RuntimeStatusResponse) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *RuntimeStatusResponse) GetStatus() RuntimeStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return RuntimeStatusResponse_STARTING
}

func (x *RuntimeStatusResponse) GetCapacityInBytes() uint64 {
	if x != nil {
		return x.CapacityInBytes
	}
	return 0
}

func (x *RuntimeStatusResponse) GetMaxLoadingConcurrency() uint32 {
	if x != nil {
		return x.MaxLoadingConcurrency
	}
	return 0
}

func (x *RuntimeStatusResponse) GetModelLoadingTimeoutMs() uint32 {
	if x != nil {
		return x.ModelLoadingTimeoutMs
	}
	return 0
}

func (x *RuntimeStatusResponse) GetDefaultModelSizeInBytes() uint64 {
	if x != nil {
		return x.DefaultModelSizeInBytes
	}
	return 0
}

func (x *RuntimeStatusResponse) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

func (x *RuntimeStatusResponse) GetNumericRuntimeVersion() uint64 {
	if x != nil {
		return x.NumericRuntimeVersion
	}
	return 0
}

func (x *RuntimeStatusResponse) GetMethodInfos() map[string]*RuntimeStatusResponse_MethodInfo {
	if x != nil {
		return x.MethodInfos
	}
	return nil
}

func (x *RuntimeStatusResponse) GetLimitModelConcurrency() bool {
	if x != nil {
		return x.LimitModelConcurrency
	}
	return false
}

type RuntimeStatusResponse_MethodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// optional
	IdInjectionPath []uint32 `protobuf:"varint,1,rep,packed,name=idInjectionPath,proto3" json:"idInjectionPath,omitempty"`
}

func (x *RuntimeStatusResponse_MethodInfo) Reset() {
	*x = RuntimeStatusResponse_MethodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_runtime_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeStatusResponse_MethodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStatusResponse_MethodInfo) ProtoMessage() {}

func (x *RuntimeStatusResponse_MethodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_model_runtime_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStatusResponse_MethodInfo.ProtoReflect.Descriptor instead.
func (*RuntimeStatusResponse_MethodInfo) Descriptor() ([]byte, []int) {
	return file_model_runtime_proto_rawDescGZIP(), []int{9, 0}
}

func (x *RuntimeStatusResponse_MethodInfo) GetIdInjectionPath() []uint32 {
	if x != nil {
		return x.IdInjectionPath
	}
	return nil
}

var File_model_runtime_proto protoreflect.FileDescriptor

var file_model_runtime_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2d, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6d, 0x65, 0x73, 0x68, 0x22, 0x84, 0x01, 0x0a,
	0x10, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x4b, 0x65, 0x79, 0x22, 0x5d, 0x0a, 0x11, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x69, 0x7a, 0x65,
	0x49, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73,
	0x69, 0x7a, 0x65, 0x49, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61,
	0x78, 0x43, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x22, 0x2e, 0x0a, 0x12, 0x55, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x17, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x4b, 0x65, 0x79, 0x22, 0x3c, 0x0a, 0x18, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x69, 0x7a, 0x65, 0x49, 0x6e, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73, 0x69, 0x7a, 0x65, 0x49, 0x6e,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x2c, 0x0a, 0x10, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x69,
	0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x69, 0x7a, 0x65,
	0x49, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73,
	0x69, 0x7a, 0x65, 0x49, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xda, 0x05, 0x0a, 0x15, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x6d,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x61, 0x70,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x15, 0x6d, 0x61, 0x78, 0x4c, 0x6f, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x43, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x15, 0x6d, 0x61, 0x78, 0x4c, 0x6f, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6f,
	0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x34, 0x0a, 0x15, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x4c, 0x6f, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x4d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x15, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4c,
	0x6f, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x12,
	0x38, 0x0a, 0x17, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53,
	0x69, 0x7a, 0x65, 0x49, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x17, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x69,
	0x7a, 0x65, 0x49, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x34, 0x0a, 0x15, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x15, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x4f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6d,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x34, 0x0a, 0x15, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x1a, 0x36,
	0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0f,
	0x69, 0x64, 0x49, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0f, 0x69, 0x64, 0x49, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x1a, 0x67, 0x0a, 0x10, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3d, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x6d,
	0x65, 0x73, 0x68, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x2e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41,
	0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x32,
	0xff, 0x02, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x40, 0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x17, 0x2e,
	0x6d, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4c,
	0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x75, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x19, 0x2e, 0x6d, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x55, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d,
	0x6d, 0x65, 0x73, 0x68, 0x2e, 0x55, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x10, 0x70, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e,
	0x2e, 0x6d, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x6d, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x40, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x17,
	0x2e, 0x6d, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x6d, 0x65, 0x73, 0x68, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0d, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x2e, 0x6d, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x52, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1b, 0x0a, 0x17, 0x69, 0x6f, 0x2e, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x61, 0x70, 0x69, 0x50, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_runtime_proto_rawDescOnce sync.Once
	file_model_runtime_proto_rawDescData = file_model_runtime_proto_rawDesc
)

func file_model_runtime_proto_rawDescGZIP() []byte {
	file_model_runtime_proto_rawDescOnce.Do(func() {
		file_model_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_runtime_proto_rawDescData)
	})
	return file_model_runtime_proto_rawDescData
}

var file_model_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_model_runtime_proto_goTypes = []interface{}{
	(RuntimeStatusResponse_Status)(0),        // 0: mmesh.RuntimeStatusResponse.Status
	(*LoadModelRequest)(nil),                 // 1: mmesh.LoadModelRequest
	(*LoadModelResponse)(nil),                // 2: mmesh.LoadModelResponse
	(*UnloadModelRequest)(nil),               // 3: mmesh.UnloadModelRequest
	(*UnloadModelResponse)(nil),              // 4: mmesh.UnloadModelResponse
	(*PredictModelSizeRequest)(nil),          // 5: mmesh.PredictModelSizeRequest
	(*PredictModelSizeResponse)(nil),         // 6: mmesh.PredictModelSizeResponse
	(*ModelSizeRequest)(nil),                 // 7: mmesh.ModelSizeRequest
	(*ModelSizeResponse)(nil),                // 8: mmesh.ModelSizeResponse
	(*RuntimeStatusRequest)(nil),             // 9: mmesh.RuntimeStatusRequest
	(*RuntimeStatusResponse)(nil),            // 10: mmesh.RuntimeStatusResponse
	(*RuntimeStatusResponse_MethodInfo)(nil), // 11: mmesh.RuntimeStatusResponse.MethodInfo
	nil,                                      // 12: mmesh.RuntimeStatusResponse.MethodInfosEntry
}
var file_model_runtime_proto_depIdxs = []int32{
	0,  // 0: mmesh.RuntimeStatusResponse.status:type_name -> mmesh.RuntimeStatusResponse.Status
	12, // 1: mmesh.RuntimeStatusResponse.methodInfos:type_name -> mmesh.RuntimeStatusResponse.MethodInfosEntry
	11, // 2: mmesh.RuntimeStatusResponse.MethodInfosEntry.value:type_name -> mmesh.RuntimeStatusResponse.MethodInfo
	1,  // 3: mmesh.ModelRuntime.loadModel:input_type -> mmesh.LoadModelRequest
	3,  // 4: mmesh.ModelRuntime.unloadModel:input_type -> mmesh.UnloadModelRequest
	5,  // 5: mmesh.ModelRuntime.predictModelSize:input_type -> mmesh.PredictModelSizeRequest
	7,  // 6: mmesh.ModelRuntime.modelSize:input_type -> mmesh.ModelSizeRequest
	9,  // 7: mmesh.ModelRuntime.runtimeStatus:input_type -> mmesh.RuntimeStatusRequest
	2,  // 8: mmesh.ModelRuntime.loadModel:output_type -> mmesh.LoadModelResponse
	4,  // 9: mmesh.ModelRuntime.unloadModel:output_type -> mmesh.UnloadModelResponse
	6,  // 10: mmesh.ModelRuntime.predictModelSize:output_type -> mmesh.PredictModelSizeResponse
	8,  // 11: mmesh.ModelRuntime.modelSize:output_type -> mmesh.ModelSizeResponse
	10, // 12: mmesh.ModelRuntime.runtimeStatus:output_type -> mmesh.RuntimeStatusResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_model_runtime_proto_init() }
func file_model_runtime_proto_init() {
	if File_model_runtime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_runtime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_runtime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadModelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_runtime_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnloadModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_runtime_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnloadModelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_runtime_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictModelSizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_runtime_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PredictModelSizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_runtime_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelSizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_runtime_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelSizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_runtime_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_runtime_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_runtime_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeStatusResponse_MethodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_runtime_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_runtime_proto_goTypes,
		DependencyIndexes: file_model_runtime_proto_depIdxs,
		EnumInfos:         file_model_runtime_proto_enumTypes,
		MessageInfos:      file_model_runtime_proto_msgTypes,
	}.Build()
	File_model_runtime_proto = out.File
	file_model_runtime_proto_rawDesc = nil
	file_model_runtime_proto_goTypes = nil
	file_model_runtime_proto_depIdxs = nil
}
