name: Test

on:
  pull_request:
    branches:
      - main
      - "release-[0-9].[0-9]+"
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build dev image
        run: make build.develop

      - name: Run lint
        run: ./scripts/develop.sh make fmt

      - name: Run unit test
        run: ./scripts/develop.sh make test
